# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    # Install Netlify CLI (if not already installed)
    npm install -g netlify-cli

    # Log in to your Netlify account (replace with your own Netlify access token)
    netlify login -t 6V4fnHVPBkNBklnm7jQLWKdcqb0oVbtLVGOgoWbXX1Y

    # Deploy to Netlify
    netlify deploy --prod
  displayName: 'Build and Deploy to Netlify'
